### ISSUE TITLE
Amazing, but there is a problem...

### ISSUE THREAD

**Issue by explodes** [jasonpolites/gesture-imageview#1]
For some reason I cannot fill_parent with the height of the image...

**Comment by jasonpolites** [comment]
Hmm.. ok. I'll look into it.  Thanks for reporting.

**Comment by explodes** [comment]
Cool, ill send you details for replicating it tomorrow...

**Comment by jasonpolites** [comment]
Just looking at the code, I realized (remembered) that this behavior is by design.

If you FILL_PARENT on both width and height, your image will be distorted (unless it's exactly the same dimensions as the device, which will obviously not be true for all devices).

When the device is in portrait view, the width is taken from your config, and the height is calculated based on the size of the image.  

When the device is in landscape view, the height is taken from your config, and the width is calculated based on the size of the image.  

You can see this here:

https://github.com/jasonpolites/gesture-imageview/blob/master/main/src/com/polites/android/GestureImageView.java#L77

**Comment by explodes** [comment]
Ah, ok, thanks!

**Comment by jasonpolites** [comment]
Addendum:

There was actually a bug in relation to this.  The fill_parent option was not being honored correctly when rendering an image on it's own.  That is, the image would not zoom to fill the view even if fill_parent was specified.  This has been fixed.
